#!/bin/csh
#-------------------------------------------------
#    removeBraces <filefile_name_prefix> 
#  This removes the '[' ']' from a file
#-------------------------------------------------
set filename = $argv[1]

echo "file is " $filename
if ($#argv != 1) then
  echo " removeBraces <file_name>"
  exit(0)
endif

sed 's/\[//g' $filename | sed 's/\]//g' >$filename.tmp
mv $filename.tmp $filename
exit
