message("SRC dir = ${Vaango_SOURCE_DIR}")
message("BIN dir = ${Vaango_BINARY_DIR}")
find_package(PythonInterp REQUIRED)
file(MAKE_DIRECTORY ${Vaango_BINARY_DIR}/TestData)
set(components "${Vaango_SOURCE_DIR}/R_Tester/helpers/selectComponents.sh ${Vaango_SOURCE_DIR}/R_Tester")
set(IS_DEBUG "no")
set(SCI_MALLOC_ON "yes")
set(MAKE_PARALLELISM 4)
set(python_command "PYTHONPATH=${Vaango_SOURCE_DIR}/R_Tester/toplevel;${Vaango_SOURCE_DIR}/R_Tester python ${Vaango_SOURCE_DIR}/R_Tester/toplevel/generateGoldStandards.py -b ${Vaango_BINARY_DIR} -s ${Vaango_SOURCE_DIR} -t MPM -v")
message("CMD = ${python_command}")
execute_process(COMMAND ${python_command} RESULT_VARIABLE CMD_RESULT)
#if(CMD_RESULT)
#  message(FATAL_ERROR "Error running gold standards")
#endif()

